spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://localhost:3306/cacss?serverTimezone=GMT%2B8 
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.newsoft.pojo
  configuration:    map-underscore-to-camel-case: true #开启驼峰命名
    #myabtis分页插件配置
  pagehelper: 
    helper-dialect: mysql  #数据库
    reasonable: true
    support-methods-arguments: true
    params: count=countSql    